# Generated by Django 5.2.6 on 2025-09-09 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "model_providers",
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(max_length=200, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "رایگان"),
                            ("basic", "پایه"),
                            ("premium", "پریمیوم"),
                            ("enterprise", "سازمانی"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("max_requests_per_minute", models.IntegerField(default=60)),
                ("max_tokens_per_minute", models.IntegerField(default=150000)),
                ("max_tokens", models.IntegerField(default=4096)),
                ("max_input_tokens", models.IntegerField(default=4096)),
                ("max_output_tokens", models.IntegerField(default=4096)),
                ("supports_vision", models.BooleanField(default=False)),
                ("supports_function_calling", models.BooleanField(default=False)),
                ("supports_tool_choice", models.BooleanField(default=False)),
                ("supports_response_schema", models.BooleanField(default=False)),
                ("pricing_data", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.modelprovider",
                    ),
                ),
            ],
            options={
                "db_table": "ai_models",
                "ordering": ["provider__name", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="ModelUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("request_timestamp", models.DateTimeField(auto_now_add=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.aimodel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "model_usage_logs",
                "indexes": [
                    models.Index(
                        fields=["user", "model", "request_timestamp"],
                        name="model_usage_user_id_5241fc_idx",
                    ),
                    models.Index(
                        fields=["session_key", "model", "request_timestamp"],
                        name="model_usage_session_aef962_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserModelPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_rate_limit", models.IntegerField(blank=True, null=True)),
                ("daily_limit", models.IntegerField(blank=True, null=True)),
                ("monthly_limit", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.aimodel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_model_permissions",
                "unique_together": {("user", "model")},
            },
        ),
    ]
