# Generated by Django 5.2.6 on 2025-09-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="model_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
