# Generated by Django 5.2.6 on 2025-09-07 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_model_name_message_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("id",)},
        ),
        migrations.AlterField(
            model_name="conversation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="مالک گفتگو (در صورت ورود). برای مهمان\u200cها خالی می\u200cماند.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.conversation"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="model_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="provider",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("working", "Working"),
                    ("streaming", "Streaming"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="done",
                max_length=16,
            ),
        ),
    ]
